// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package rpsls_gen

import (
	"rpsls/rpslsapi"
	"rpsls/rpslsapi/http"
	"rpsls/rpslsapi/storage/neo4j"
	"rpsls/rpslsapi/storage/redis"
)

// Injectors from wire.go:

func InitServer() (http.Server, func()) {
	dbClient, cleanup := neo4j.NewDbClient()
	choiceStore := neo4j.NewChoiceStore(dbClient)
	randomizerClient := http.NewRandomizerClient()
	externalRandomizerService := rpslsapi.NewExternalRandomizerService(randomizerClient)
	choiceService := rpslsapi.NewChoiceService(choiceStore, externalRandomizerService)
	choiceHandler := http.NewChoiceHandler(choiceService)
	roundStore := neo4j.NewRoundStore(dbClient)
	client := redis.NewClient()
	scoreboardStore := redis.NewScoreboardStore(client)
	scoreboardService := rpslsapi.NewScoreboardService(scoreboardStore)
	roundService := rpslsapi.NewRoundService(roundStore, choiceService, scoreboardService)
	roundHandler := http.NewRoundHandler(roundService)
	scoreboardHandler := http.NewScoreboardHandler(scoreboardService)
	router := http.NewRouter(choiceHandler, roundHandler, scoreboardHandler)
	server := http.NewServer(router)
	return server, func() {
		cleanup()
	}
}
